module.exports.modelMap = [
    {
        id: 1,
        model: 'iPhone 7',
        price: 18,
        memory: null,
    },
    {
        id: 2,
        model: 'iPhone 7',
        price: 18,
        memory: 32,
    },
    {
        id: 3,
        model: 'iPhone 7',
        price: 22,
        memory: 128,
    },
    {
        id: 4,
        model: 'iPhone 7',
        price: 26,
        memory: 256,
    },
    {
        id: 5,
        model: 'iPhone 7 Plus',
        price: 26,
        memory: null,
    },
    {
        id: 6,
        model: 'iPhone 7 Plus',
        price: 26,
        memory: 32,
    },
    {
        id: 7,
        model: 'iPhone 7 Plus',
        price: 32,
        memory: 128,
    },
    {
        id: 8,
        model: 'iPhone 7 Plus',
        price: 38,
        memory: 256,
    },
    {
        id: 5,
        model: 'iPhone 7+',
        price: 26,
        memory: null,
    },
    {
        id: 6,
        model: 'iPhone 7+',
        price: 26,
        memory: 32,
    },
    {
        id: 7,
        model: 'iPhone 7+',
        price: 32,
        memory: 128,
    },
    {
        id: 8,
        model: 'iPhone 7+',
        price: 38,
        memory: 256,
    },
    {
        id: 9,
        model: 'iPhone 8',
        price: 35,
        memory: null,
    },
    {
        id: 10,
        model: 'iPhone 8',
        price: 35,
        memory: 64,
    },
    {
        id: 11,
        model: 'iPhone 8',
        price: 45,
        memory: 128,
    },
    {
        id: 12,
        model: 'iPhone 8',
        price: 54,
        memory: 256,
    },
    {
        id: 13,
        model: 'iPhone 8 Plus',
        price: 51,
        memory: null,
    },
    {
        id: 14,
        model: 'iPhone 8 Plus',
        price: 51,
        memory: 64,
    },
    {
        id: 15,
        model: 'iPhone 8 Plus',
        price: 63,
        memory: 128,
    },
    {
        id: 16,
        model: 'iPhone 8 Plus',
        price: 73,
        memory: 256,
    },
    {
        id: 13,
        model: 'iPhone 8+',
        price: 51,
        memory: null,
    },
    {
        id: 14,
        model: 'iPhone 8+',
        price: 51,
        memory: 64,
    },
    {
        id: 15,
        model: 'iPhone 8+',
        price: 63,
        memory: 128,
    },
    {
        id: 16,
        model: 'iPhone 8+',
        price: 73,
        memory: 256,
    },
    {
        id: 17,
        model: 'iPhone X',
        price: 72,
        memory: null,
    },
    {
        id: 18,
        model: 'iPhone X',
        price: 72,
        memory: 64,
    },
    {
        id: 19,
        model: 'iPhone X',
        price: 90,
        memory: 256,
    },
    {
        id: 20,
        model: 'iPhone XR',
        price: 76,
        memory: null,
    },
    {
        id: 21,
        model: 'iPhone XR',
        price: 76,
        memory: 64,
    },
    {
        id: 22,
        model: 'iPhone XR',
        price: 99,
        memory: 128,
    },
    {
        id: 23,
        model: 'iPhone XR',
        price: 112,
        memory: 256,
    },
    {
        id: 24,
        model: 'iPhone XS',
        price: 81,
        memory: null,
    },
    {
        id: 25,
        model: 'iPhone XS',
        price: 81,
        memory: 64,
    },
    {
        id: 26,
        model: 'iPhone XS',
        price: 103,
        memory: 256,
    },
    {
        id: 27,
        model: 'iPhone XS',
        price: 117,
        memory: 512,
    },
    {
        id: 28,
        model: 'iPhone XS Max',
        price: 108,
        memory: null,
    },
    {
        id: 29,
        model: 'iPhone XS Max',
        price: 108,
        memory: 64,
    },
    {
        id: 30,
        model: 'iPhone XS Max',
        price: 126,
        memory: 256,
    },
    {
        id: 31,
        model: 'iPhone XS Max',
        price: 139,
        memory: 512,
    },
    {
        id: 32,
        model: 'iPhone 11',
        price: 112,
        memory: null,
    },
    {
        id: 33,
        model: 'iPhone 11',
        price: 112,
        memory: 64,
    },
    {
        id: 34,
        model: 'iPhone 11',
        price: 130,
        memory: 128,
    },
    {
        id: 35,
        model: 'iPhone 11',
        price: 148,
        memory: 256,
    },
    {
        id: 36,
        model: 'iPhone 11 Pro',
        price: 139,
        memory: null,
    },
    {
        id: 37,
        model: 'iPhone 11 Pro',
        price: 139,
        memory: 64,
    },
    {
        id: 38,
        model: 'iPhone 11 Pro',
        price: 166,
        memory: 256,
    },
    {
        id: 39,
        model: 'iPhone 11 Pro',
        price: 193,
        memory: 512,
    },
    {
        id: 40,
        model: 'iPhone 11 Pro Max',
        price: 171,
        memory: null,
    },
    {
        id: 41,
        model: 'iPhone 11 Pro Max',
        price: 171,
        memory: 64,
    },
    {
        id: 42,
        model: 'iPhone 11 Pro Max',
        price: 193,
        memory: 256,
    },
    {
        id: 43,
        model: 'iPhone 11 Pro Max',
        price: 216,
        memory: 512,
    },
    {
        id: 44,
        model: 'iPhone SE 2nd Gen',
        price: 49,
        memory: null,
    },
    {
        id: 45,
        model: 'iPhone SE 2nd Gen',
        price: 49,
        memory: 64,
    },
    {
        id: 46,
        model: 'iPhone SE 2nd Gen',
        price: 63,
        memory: 128,
    },
    {
        id: 47,
        model: 'iPhone SE 2nd Gen',
        price: 81,
        memory: 256,
    },
    {
        id: 48,
        model: 'iPhone 12',
        price: 153,
        memory: null,
    },
    {
        id: 49,
        model: 'iPhone 12',
        price: 153,
        memory: 64,
    },
    {
        id: 50,
        model: 'iPhone 12',
        price: 175,
        memory: 128,
    },
    {
        id: 51,
        model: 'iPhone 12',
        price: 202,
        memory: 256,
    },
    {
        id: 52,
        model: 'iPhone 12 Mini',
        price: 130,
        memory: null,
    },
    {
        id: 53,
        model: 'iPhone 12 Mini',
        price: 130,
        memory: 64,
    },
    {
        id: 54,
        model: 'iPhone 12 Mini',
        price: 153,
        memory: 128,
    },
    {
        id: 55,
        model: 'iPhone 12 Mini',
        price: 175,
        memory: 256,
    },
    {
        id: 56,
        model: 'iPhone 12 Pro',
        price: 198,
        memory: null,
    },
    {
        id: 57,
        model: 'iPhone 12 Pro',
        price: 198,
        memory: 128,
    },
    {
        id: 58,
        model: 'iPhone 12 Pro',
        price: 220,
        memory: 256,
    },
    {
        id: 59,
        model: 'iPhone 12 Pro',
        price: 247,
        memory: 512,
    },
    {
        id: 60,
        model: 'iPhone 12 Pro Max',
        price: 238,
        memory: null,
    },
    {
        id: 61,
        model: 'iPhone 12 Pro Max',
        price: 238,
        memory: 128,
    },
    {
        id: 62,
        model: 'iPhone 12 Pro Max',
        price: 261,
        memory: 256,
    },
    {
        id: 63,
        model: 'iPhone 12 Pro Max',
        price: 288,
        memory: 512,
    },
    {
        id: 64,
        model: 'iPhone 13',
        price: 234,
        memory: null,
    },
    {
        id: 65,
        model: 'iPhone 13',
        price: 234,
        memory: 128,
    },
    {
        id: 66,
        model: 'iPhone 13',
        price: 261,
        memory: 256,
    },
    {
        id: 67,
        model: 'iPhone 13',
        price: 292,
        memory: 512,
    },
    {
        id: 68,
        model: 'iPhone 13 Mini',
        price: 198,
        memory: null,
    },
    {
        id: 69,
        model: 'iPhone 13 Mini',
        price: 198,
        memory: 128,
    },
    {
        id: 70,
        model: 'iPhone 13 Mini',
        price: 225,
        memory: 256,
    },
    {
        id: 71,
        model: 'iPhone 13 Mini',
        price: 256,
        memory: 512,
    },
    {
        id: 72,
        model: 'iPhone 13 Pro',
        price: 300,
        memory: null,
    },
    {
        id: 73,
        model: 'iPhone 13 Pro',
        price: 300,
        memory: 128,
    },
    {
        id: 74,
        model: 'iPhone 13 Pro',
        price: 328,
        memory: 256,
    },
    {
        id: 75,
        model: 'iPhone 13 Pro',
        price: 360,
        memory: 512,
    },
    {
        id: 76,
        model: 'iPhone 13 Pro',
        price: 391,
        memory: 1024,
    },
    // {
    //     id: 77,
    //     model: 'iPhone 13 Pro Max',
    //     price: null,
    //     memory: null,
    // },
    // {
    //     id: 78,
    //     model: 'iPhone 13 Pro Max',
    //     price: null,
    //     memory: 128,
    // },
    // {
    //     id: 79,
    //     model: 'iPhone 13 Pro Max',
    //     price: null,
    //     memory: 256,
    // },
    // {
    //     id: 80,
    //     model: 'iPhone 13 Pro Max',
    //     price: null,
    //     memory: 512,
    // },
    // {
    //     id: 81,
    //     model: 'iPhone 13 Pro Max',
    //     price: null,
    //     memory: 1024,
    // },
    {
        id: 82,
        model: 'iPhone SE3',
        price: 126,
        memory: null,
    },
    {
        id: 83,
        model: 'iPhone SE3',
        price: 126,
        memory: 64,
    },
    {
        id: 84,
        model: 'iPhone SE3',
        price: 157,
        memory: 128,
    },
    {
        id: 85,
        model: 'iPhone SE3',
        price: 193,
        memory: 256,
    },
    {
        id: 82,
        model: 'iPhone SE 3',
        price: 126,
        memory: null,
    },
    {
        id: 83,
        model: 'iPhone SE 3',
        price: 126,
        memory: 64,
    },
    {
        id: 84,
        model: 'iPhone SE 3',
        price: 157,
        memory: 128,
    },
    {
        id: 85,
        model: 'iPhone SE 3',
        price: 193,
        memory: 256,
    },
    {
        id: 82,
        model: 'iPhone SE 3rd Gen',
        price: 126,
        memory: null,
    },
    {
        id: 83,
        model: 'iPhone SE 3rd Gen',
        price: 126,
        memory: 64,
    },
    {
        id: 84,
        model: 'iPhone SE 3rd Gen',
        price: 157,
        memory: 128,
    },
    {
        id: 85,
        model: 'iPhone SE 3rd Gen',
        price: 193,
        memory: 256,
    },
];
